### ISSUE TITLE
Manage the app from an Iphone 

### ISSUE THREAD

**Issue by rebecacuestaestepar** [darfepe/GESPRO_Practica_2_Curso_2024_2025#11]

**Comment by darfepe** [comment]
¿Cómo funciona esta tarea?

**Comment by rebecacuestaestepar** [comment]
Trata del manejo de la aplicación sobre un dispositivo móvil, en este caso el Iphone.

**Comment by alvaroooper** [comment]
> Trata del manejo de la aplicación sobre un dispositivo móvil, en este caso el Iphone.

Yo también lo tendré en cuenta, perfecto
