### ISSUE TITLE
Transfer money

### ISSUE THREAD

**Issue by darfepe** [darfepe/GESPRO_Practica_2_Curso_2024_2025#13]

**Comment by alvaroooper** [comment]
¿Cómo se va a transferir el dinero?

**Comment by darfepe** [comment]
Mediante transferencia bancaria.

**Comment by rebecacuestaestepar** [comment]
¿Se puede transferir el dinero mediante bizum?

**Comment by darfepe** [comment]
> ¿Se puede transferir el dinero mediante bizum?

Sí.
