### ISSUE TITLE
Get bank details

### ISSUE THREAD

**Issue by alvaroooper** [darfepe/GESPRO_Practica_2_Curso_2024_2025#17]

**Comment by rebecacuestaestepar** [comment]
¿De que trata esta tarea?

**Comment by alvaroooper** [comment]
> ¿De que trata esta tarea?

De añadir detalles sobre el banco

**Comment by darfepe** [comment]
> > ¿De que trata esta tarea?
> 
> De añadir detalles sobre el banco

Perfecta explicación.
